"""changed Cat model 'title' to 'name'

Revision ID: 6192789dfcc7
Revises: 084a62d080ce
Create Date: 2025-04-24 10:52:22.072589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6192789dfcc7'
down_revision = '084a62d080ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
